server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://139.224.115.237:3306/generator?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: zhangC1997
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

generator:
  package: com.zkys
  template:
    base-path: mybatis-plus
    output-paths: |
      Entity.java.vm: src/main/java/{packagePath}/model/pojos/{className}info.java
      Mapper.java.vm: src/main/java/{packagePath}/mappers/{className}Mapper.java
      Service.java.vm: src/main/java/{packagePath}/service/{className}Service.java
      ServiceImpl.java.vm: src/main/java/{packagePath}/service/impl/{className}ServiceImpl.java
      Controller.java.vm: src/main/java/{packagePath}/controller/v1/{className}Contoller.java
      ControllerApi.java.vm: src/main/java/{packagePath}/controller/api/{className}ContollerApi.java
